### ISSUE TITLE
About SRN

### ISSUE THREAD

**Issue by SolicTous** [albertobagnacani/Deblur#1]
Hello, thanks for the presentation.
I'm trying to deploy SRN-Deblur with recurrent layers because of big-scale image processing.

How to prevent "rainbow" artifacts. If I just delete recurrent layers, SRN will be bad on big-scale images.
Do you know anything about it?

**Comment by albertobagnacani** [comment]
Hi Marsel,

I'm sorry but I cannot help you with this problem.

Sincerely,
Alberto
________________________________
From: Marsel Iamaev ***@***.***>
Sent: Tuesday, March 23, 2021 7:06:39 AM
To: albertobagnacani/DeepDeblur ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [albertobagnacani/DeepDeblur] About SRN (#1)


Hello, thanks for the presentation.
I'm trying to deploy SRN-Deblur with recurrent layers because of big-scale image processing.

How to prevent "rainbow" artifacts. If I just delete recurrent layers, SRN will be bad on big-scale images.
Do you know anything about it?
